general_info_keys = [
    'reg_number',
    'type',
    'trade_name',
    'kind',
    'reg_date',
    'term',
    'expiration_date',
    'producer_name',
    'country',
    'drug_type_id',
    'int_name',
    'act_name',
    'dosage_form_name',
    'dosage',
    'storage_term',
    'nd_name',
    'nd_number']